### ISSUE TITLE
v0.2.0 Roadmap

### ISSUE THREAD

**Issue by altayaydemir** [barbar/vortigern#93]
**Core**
- [x] [Upgrade to TypeScript 2.0](https://github.com/barbar/vortigern/issues/86)
- [ ] [Fix nested class problem](https://github.com/barbar/vortigern/issues/71)

**Optional**
- [ ] Use Jest & Enzyme instead of existing testing setup.
- [ ] Keep redux-thunk, use async-await for handling side effects. (or migrate to redux-saga?)
- [ ] Optimize webpack config, share redundant parts between dev and prod configs.

---

@batuhan @ufukomer  anything to add?

**Comment by ufukomer** [comment]
[Yarn](https://github.com/yarnpkg/yarn)?

**Comment by batuhan** [comment]
Is there anything special we'll need to do to switch to yarn? Asking because of TypeScript. Normally, all we'll have to do is ```yarn``` and commit the lock file. Everything should work seamlessly.

**Comment by altayaydemir** [comment]
😭 [THIS](https://github.com/yarnpkg/yarn/issues/1164) 😭

**Comment by altayaydemir** [comment]
yarn is ok now.
